export { Answer, AuthPathway, Pathway, isAnsweredValue, answerAsString, answerAsArray, answerIsOneOf } from './types';
export type { Answers, AnswerValue } from './types';
export { computeDetermination } from './computeDetermination';
export type { DeterminationResult } from './computeDetermination';
export { computeDerivedState } from './computeDerivedState';
export { getBlockFields, getBlocks } from './getQuestions';
export type { DerivedState, AssessmentField, Block } from './getQuestions';
export { changeTaxonomy, CATEGORY_INTENDED_USE, CATEGORY_POST_MARKET, CHANGE_MONITORING_THRESHOLD_PREFIX } from './changeTaxonomy';
export type { ChangeTypeDefinition, ChangeCategoryDefinition } from './changeTaxonomy';
export { parseNumericAnswer, parseSources, pushUnique } from './utils';
export { applyCascadeClearing, applyCascadeClearingBatch } from './applyCascadeClearing';
export { joinWithAnd, getChangeLabel, getSelectedChangeContext } from './change-utils';
export type { SelectedChangeContext } from './change-utils';
export { classifySource } from './source-classification';
export type { SourceClass } from './source-classification';
export { computeEvidenceGaps } from './evidence-gaps';
export type { GapSeverity, EvidenceGap } from './evidence-gaps';
export { buildExpertReviewItems, buildEvidenceGapInsightItems } from './review-insights';
export type { ReviewInsightItem, EvidenceGapInsightItem } from './review-insights';
export { buildCaseSpecificReasoning } from './case-specific-reasoning';
export type { CaseSpecificReasoning } from './case-specific-reasoning';
export { splitReportNarrative, buildAssessmentBasis, buildAssessmentBasisView } from './report-basis';
export type { ReportNarrativeView, AssessmentRecordFact, AssessmentBasisView } from './report-basis';
export { getSections, getHandoffTitle, getHandoffDesc, getPreparationPackageLabel } from './handoff-checklist';
export type { ChecklistSection } from './handoff-checklist';
export { guidanceLinks, findGuidanceLink, getSourceBadge } from './content';
export { ruleReasoningLibrary, fieldReasoningLibrary } from './content';
export { docRequirements } from './content';
export { guidanceLinkPatterns } from './content';
export type { RefPattern } from './content';
