export { Answer, AuthPathway, Pathway, isAnsweredValue, answerAsString, answerAsArray, answerIsOneOf } from './types.js';
export type { Answers, AnswerValue } from './types.js';
export { computeDetermination } from './computeDetermination.js';
export type { DeterminationResult } from './computeDetermination.js';
export { computeDerivedState } from './computeDerivedState.js';
export { getBlockFields, getBlocks } from './getQuestions.js';
export type { DerivedState, AssessmentField, Block } from './getQuestions.js';
export { changeTaxonomy, CATEGORY_INTENDED_USE, CATEGORY_POST_MARKET, CHANGE_MONITORING_THRESHOLD_PREFIX } from './changeTaxonomy.js';
export type { ChangeTypeDefinition, ChangeCategoryDefinition } from './changeTaxonomy.js';
export { parseNumericAnswer, parseSources, pushUnique } from './utils.js';
export { applyCascadeClearing, applyCascadeClearingBatch } from './applyCascadeClearing.js';
export { joinWithAnd, getChangeLabel, getSelectedChangeContext } from './change-utils.js';
export type { SelectedChangeContext } from './change-utils.js';
export { classifySource } from './source-classification.js';
export type { SourceClass } from './source-classification.js';
export { computeEvidenceGaps } from './evidence-gaps.js';
export type { GapSeverity, EvidenceGap } from './evidence-gaps.js';
export { buildExpertReviewItems, buildEvidenceGapInsightItems } from './review-insights.js';
export type { ReviewInsightItem, EvidenceGapInsightItem } from './review-insights.js';
export { buildCaseSpecificReasoning } from './case-specific-reasoning.js';
export type { CaseSpecificReasoning } from './case-specific-reasoning.js';
export { splitReportNarrative, buildAssessmentBasis, buildAssessmentBasisView } from './report-basis.js';
export type { ReportNarrativeView, AssessmentRecordFact, AssessmentBasisView } from './report-basis.js';
export { getSections, getHandoffTitle, getHandoffDesc, getPreparationPackageLabel } from './handoff-checklist.js';
export type { ChecklistSection } from './handoff-checklist.js';
export { guidanceLinks, findGuidanceLink, getSourceBadge } from './content/index.js';
export { ruleReasoningLibrary, fieldReasoningLibrary } from './content/index.js';
export { docRequirements } from './content/index.js';
export { guidanceLinkPatterns } from './content/index.js';
export type { RefPattern } from './content/index.js';
export { SAMPLE_CASES } from './demo-cases.js';
export type { SampleCaseDefinition, AuthPathwayValue, PathwayValue } from './demo-cases.js';
