import { Answer, AuthPathway, Pathway } from '../lib/assessment-engine';
import type { SampleCaseDefinition } from './types';

export const SAMPLE_CASES: SampleCaseDefinition[] = [
  {
    id: 'SC-01',
    title: 'Chest CT calibration refit',
    authPathway: AuthPathway.FiveOneZeroK,
    shortScenario: 'Probability recalibration without retraining or threshold movement.',
    keyAmbiguity: 'Calibration changes can be mistaken for threshold or broader clinical-output changes.',
    expectedPathway: Pathway.LetterToFile,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C10',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.FiveOneZeroK,
      A1b: 'K221301',
      A1c: 'v4.2 cleared build',
      A1d: 'The device is intended to assist radiologists in detecting suspected lung nodules on chest CT images in adult patients (18 years and older). The device does not provide a diagnosis.',
      A2: Answer.No,
      A6: ['Deep Learning (e.g., CNN, RNN)'],
      A8: '1',
      B1: 'Clinical Output & Decision Thresholds',
      B2: 'Confidence score recalibration',
      B3: Answer.No,
      B4: 'Replace Platt scaling with isotonic regression using a locked retrospective dataset from already-cleared sites; no retraining, threshold move, or labeling change.',
      C1: Answer.No,
      C2: Answer.No,
      C3: Answer.No,
      C4: Answer.No,
      C5: Answer.No,
      C6: Answer.No,
      C10: Answer.No,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-02',
    title: 'Retinal normalization harmonization',
    authPathway: AuthPathway.DeNovo,
    shortScenario: 'Input normalization updated to reduce cleared-camera firmware drift.',
    keyAmbiguity: 'The change can look like a new acquisition-parameter problem even though it stays inside the cleared device type.',
    expectedPathway: Pathway.LetterToFile,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C0_DN1', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C10',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.DeNovo,
      A1b: 'DEN230045',
      A1c: 'v2.7 cleared build',
      A1d: 'The device is intended to assist qualified eye-care professionals in detecting more than mild diabetic retinopathy from retinal fundus images in adults. The device does not replace clinical judgment.',
      A2: Answer.No,
      A6: ['Deep Learning (e.g., CNN, RNN)'],
      A8: '2',
      B1: 'Preprocessing & Feature Engineering',
      B2: 'Normalization change',
      B3: Answer.No,
      B4: 'Update illumination and channel normalization to reduce vendor firmware drift for already-cleared fundus camera families without changing inputs or intended users.',
      C0_DN1: Answer.Yes,
      C1: Answer.No,
      C2: Answer.No,
      C3: Answer.No,
      C4: Answer.No,
      C5: Answer.No,
      C6: Answer.No,
      C10: Answer.No,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-03',
    title: 'Sepsis alert operating-point retune inside PCCP',
    authPathway: AuthPathway.FiveOneZeroK,
    shortScenario: 'Alert threshold retuned within an already-authorized PCCP envelope.',
    keyAmbiguity: 'A bounded threshold change still shifts sensitivity and workflow burden, so it cannot be treated as automatically documentation-only.',
    expectedPathway: Pathway.ImplementPCCP,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C10',
      'P1', 'P2', 'P3', 'P4', 'P5',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.FiveOneZeroK,
      A1b: 'K233018',
      A1c: 'v5.1 cleared baseline',
      A1d: 'The device is intended to provide a sepsis risk score to hospital clinicians for adult inpatients as an adjunct to clinical assessment. The device does not provide a diagnosis.',
      A2: Answer.Yes,
      A6: ['Traditional ML (e.g., random forest, SVM)', 'Ensemble / Multi-Model'],
      A8: '3',
      B1: 'Clinical Output & Decision Thresholds',
      B2: 'Decision threshold adjustment',
      B3: Answer.No,
      B4: 'Raise the alert threshold within the prospectively authorized operating range to reduce false alerts in a high-acuity oncology unit after post-market review.',
      C1: Answer.No,
      C2: Answer.No,
      C3: Answer.No,
      C4: Answer.No,
      C5: Answer.No,
      C6: Answer.Yes,
      C10: Answer.No,
      P1: Answer.Yes,
      P2: Answer.Yes,
      P3: Answer.Yes,
      P4: Answer.Yes,
      P5: Answer.Yes,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-04',
    title: 'PMA GenAI prompt/guardrail update inside PCCP',
    authPathway: AuthPathway.PMA,
    shortScenario: 'Prompt and guardrail tightening for a PMA GenAI drafting device, executed under an authorized PCCP.',
    keyAmbiguity: 'These are configuration changes, but they still affect PMA safety/effectiveness and GenAI behavior.',
    expectedPathway: Pathway.ImplementPCCP,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C_PMA1', 'C_PMA2', 'C_PMA3', 'C_PMA4',
      'P1', 'P2', 'P3', 'P4', 'P5',
      'D1', 'D2', 'D3', 'D4', 'D5',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.PMA,
      A1b: 'P210014',
      A1c: 'v3.4 approved baseline',
      A1d: 'The device is intended to generate draft structured imaging follow-up summaries for radiologists reviewing adult chest CT studies, for clinician review before finalization.',
      A2: Answer.Yes,
      A6: ['LLM / Foundation Model', 'Generative AI'],
      A8: '2',
      B1: 'Foundation Model / Generative AI',
      B2: 'Guardrail / safety filter modification',
      B3: Answer.No,
      B4: 'Tighten the system prompt and content filters so unsupported follow-up recommendations are withheld unless explicit imaging criteria are present; no base-model swap.',
      C_PMA1: Answer.Yes,
      C_PMA2: Answer.No,
      C_PMA3: Answer.No,
      C_PMA4: '180-Day Supplement (§814.39(a) — change affecting safety/effectiveness not requiring panel-track)',
      P1: Answer.Yes,
      P2: Answer.Yes,
      P3: Answer.Yes,
      P4: Answer.Yes,
      P5: Answer.Yes,
      D1: Answer.No,
      D2: Answer.Yes,
      D3: Answer.No,
      D4: Answer.Yes,
      D5: Answer.Yes,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-05',
    title: 'PMA quantization for hardware refresh',
    authPathway: AuthPathway.PMA,
    shortScenario: 'Quantize a PMA CNN to support a processor refresh without changing the clinical function.',
    keyAmbiguity: 'Optimization work can still affect edge-case numerics, so it needs explicit PMA safety/effectiveness review.',
    expectedPathway: Pathway.PMAAnnualReport,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C_PMA1', 'C_PMA2', 'C_PMA3',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.PMA,
      A1b: 'P190220',
      A1c: 'v6.0 approved baseline',
      A1d: 'The device is intended to analyze continuous physiologic waveforms to assist clinicians in identifying clinically significant arrhythmia patterns in monitored adult patients.',
      A2: Answer.No,
      A6: ['Deep Learning (e.g., CNN, RNN)'],
      A8: '1',
      B1: 'Model Architecture',
      B2: 'Compression / quantization',
      B3: Answer.No,
      B4: 'Quantize the approved CNN for a planned processor refresh while preserving the same model structure, inputs, and clinical function.',
      C_PMA1: Answer.No,
      C_PMA2: Answer.No,
      C_PMA3: Answer.No,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-06',
    title: 'PMA backbone deepening outside PCCP',
    authPathway: AuthPathway.PMA,
    shortScenario: 'Deepen a PMA model within the same architecture family, but beyond the authorized PCCP boundary.',
    keyAmbiguity: 'It looks like a bounded same-family revision, yet the existing PCCP does not actually authorize this architecture step.',
    expectedPathway: Pathway.PMASupplementRequired,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C_PMA1', 'C_PMA2', 'C_PMA3', 'C_PMA4',
      'P1', 'P2',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.PMA,
      A1b: 'P200118',
      A1c: 'v2.9 approved baseline',
      A1d: 'The device is intended to assist cardiologists in quantifying left-ventricular function from transthoracic echocardiography in adult patients.',
      A2: Answer.Yes,
      A6: ['Deep Learning (e.g., CNN, RNN)', 'Transformer / Attention-Based'],
      A8: '2',
      B1: 'Model Architecture',
      B2: 'Architecture change (same family)',
      B3: Answer.No,
      B4: 'Move to a deeper same-family backbone with an added attention block to address misses on technically limited apical views.',
      C_PMA1: Answer.Yes,
      C_PMA2: Answer.No,
      C_PMA3: Answer.No,
      C_PMA4: '180-Day Supplement (§814.39(a) — change affecting safety/effectiveness not requiring panel-track)',
      P1: Answer.Yes,
      P2: Answer.No,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-07',
    title: 'Oncology RAG refresh with behavior shift',
    authPathway: AuthPathway.FiveOneZeroK,
    shortScenario: 'Refresh the RAG corpus and retrieval instructions for a clinician-facing oncology GenAI system.',
    keyAmbiguity: 'There is no base-model swap, but the retrieved knowledge still changes clinical behavior.',
    expectedPathway: Pathway.NewSubmission,
    expectedPccpRecommendation: true,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C10',
      'D1', 'D2', 'D3', 'D4', 'D5',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.FiveOneZeroK,
      A1b: 'K240112',
      A1c: 'v1.8 cleared baseline',
      A1d: 'The device is intended to generate draft oncology supportive-care summaries for clinician review using structured patient data and referenced institutional content. The device does not issue autonomous treatment orders.',
      A2: Answer.No,
      A6: ['LLM / Foundation Model', 'Generative AI'],
      A8: '3',
      B1: 'Foundation Model / Generative AI',
      B2: 'RAG knowledge base update',
      B3: Answer.No,
      B4: 'Refresh the RAG corpus and retrieval instructions so the model uses newer supportive-care guidance, changing how it ranks and cites prophylaxis advice in borderline neutropenia scenarios.',
      C1: Answer.No,
      C2: Answer.No,
      C3: Answer.No,
      C4: Answer.No,
      C5: Answer.No,
      C6: Answer.Yes,
      C10: Answer.No,
      D1: Answer.No,
      D2: Answer.Yes,
      D3: Answer.Yes,
      D4: Answer.No,
      D5: Answer.Yes,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-08',
    title: 'Pathology drift-correction retraining',
    authPathway: AuthPathway.DeNovo,
    shortScenario: 'Retrain a De Novo pathology model to correct post-market drift after staining and lab-mix shifts.',
    keyAmbiguity: 'The team can frame it as maintenance, but it is not a pure restore-to-spec fix and it materially changes model behavior.',
    expectedPathway: Pathway.NewSubmission,
    expectedPccpRecommendation: true,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C0_DN1', 'C1', 'C2', 'C3', 'C10',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.DeNovo,
      A1b: 'DEN220201',
      A1c: 'v3.1 cleared baseline',
      A1d: 'The device is intended to assist pathologists in triaging digitized lymph-node whole-slide images for likely metastatic involvement in adult patients.',
      A2: Answer.No,
      A6: ['Deep Learning (e.g., CNN, RNN)'],
      A8: '4',
      B1: 'Continuous Learning / Periodic Retraining',
      B2: 'Drift correction update',
      B3: Answer.No,
      B4: 'Retrain the model to correct field drift after staining-protocol and lab-mix changes reduced performance on inflammatory mimics; architecture and intended output stay the same.',
      C0_DN1: Answer.Yes,
      C1: Answer.No,
      C2: Answer.No,
      C3: Answer.Yes,
      C10: Answer.No,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
  {
    id: 'SC-09',
    title: 'Prompt change with unresolved cumulative PCCP fit',
    authPathway: AuthPathway.FiveOneZeroK,
    shortScenario: 'Prompt rewrite plus guardrail relaxation after several prior PCCP prompt changes.',
    keyAmbiguity: 'The individual modification can look PCCP-shaped, but cumulative impact remains unresolved.',
    expectedPathway: Pathway.AssessmentIncomplete,
    expectedPccpRecommendation: false,
    visibleQuestionIds: [
      'A1', 'A1b', 'A1c', 'A1d', 'A2', 'A6', 'A8',
      'B1', 'B2', 'B3', 'B4',
      'C1', 'C2', 'C3', 'C4', 'C5', 'C10',
      'P1', 'P2', 'P3', 'P4', 'P5',
      'D1', 'D2', 'D3', 'D4', 'D5',
      'E1', 'E2', 'E3', 'E4', 'E5',
    ],
    answers: {
      A1: AuthPathway.FiveOneZeroK,
      A1b: 'K241045',
      A1c: 'v2.3 cleared baseline',
      A1d: 'The device is intended to generate draft discharge medication summaries for clinician review using structured medication data and the patient chart. The device does not replace clinician medication reconciliation.',
      A2: Answer.Yes,
      A6: ['LLM / Foundation Model', 'Generative AI'],
      A8: '5',
      B1: 'Foundation Model / Generative AI',
      B2: 'Prompt / instruction template change',
      B3: Answer.No,
      B4: 'Rewrite the system prompt and relax one refusal rule so the model makes more aggressive omission checks and inferred medication-reconciliation suggestions after several prior PCCP prompt updates.',
      C1: Answer.No,
      C2: Answer.No,
      C3: Answer.No,
      C4: Answer.No,
      C5: Answer.Yes,
      C10: Answer.No,
      P1: Answer.Yes,
      P2: Answer.Yes,
      P3: Answer.Yes,
      P4: Answer.Yes,
      P5: Answer.Uncertain,
      D1: Answer.No,
      D2: Answer.Yes,
      D3: Answer.No,
      D4: Answer.Yes,
      D5: Answer.Yes,
      E1: Answer.Yes,
      E2: Answer.Yes,
      E3: Answer.No,
      E4: Answer.Yes,
      E5: Answer.No,
    },
  },
];
