/**
 * Change taxonomy — verbatim extraction from regassess_v11.html lines 758–880.
 * Each top-level key is a change category; `.types` lists specific change types.
 *
 * PCCP eligibility labels are GENERAL SUITABILITY INDICATORS based on change type alone.
 * They do NOT determine actual PCCP eligibility, which depends on: (1) whether the specific
 * change is described in the authorized PCCP, (2) whether it falls within PCCP modification
 * boundaries, (3) whether validation protocols exist, and (4) cumulative impact assessment.
 * Labels: TYPICAL = generally suitable change type for PCCP coverage if properly scoped;
 * CONDITIONAL = may be suitable depending on scope and risk; UNLIKELY = rarely suitable;
 * NO = outside PCCP scope per guidance; EXEMPT = cybersecurity exemption pathway.
 */
export const changeTaxonomy: Record<string, any> = {
  "Training Data": {
    types: [
      { name: "Additional data — same distribution", desc: "Adding more training data from existing sources matching current distribution.", example: "Adding 5,000 more chest X-rays from existing hospital partners using same equipment.", misclass: "Often confused with 'new clinical sites' when data comes from the same hospital system but a newly opened facility. If new facility = new equipment or protocols, classify under 'new clinical sites' instead.", pccp: "TYPICAL", pccpNote: "Define data quality criteria, acceptance thresholds, validation protocol." },
      { name: "Additional data — new clinical sites", desc: "Adding training data from new clinical sites not previously included.", example: "Expanding training set with data from 3 new hospitals in different regions.", misclass: "Often confused with 'expanded demographics' if new sites serve different demographics. Check clearance letter for population restrictions — if new sites introduce patients outside your cleared population, this may be a population expansion.", pccp: "CONDITIONAL", pccpNote: "PCCP must define demographic bounds + subgroup validation." },
      { name: "Additional data — expanded demographics", desc: "Adding data that expands demographic representation of the training set.", example: "Adding pediatric cases to a model originally trained only on adult populations.", misclass: "This is the most commonly misclassified change type. Teams classify demographic expansion as 'new clinical sites' when the real issue is population expansion (intended use change). If your clearance letter specifies an age range and you're expanding beyond it, this changes intended use regardless of how it's framed technically.", pccp: "CONDITIONAL", pccpNote: "May trigger intended use change. Verify against clearance letter population." },
      { name: "New modality or acquisition parameters", desc: "Adding training data from a new imaging modality or different acquisition parameters.", example: "Adding CT data to a model originally trained only on MRI.", misclass: "May be confused with 'new clinical sites' when different equipment at existing sites is involved. Adding a fundamentally different imaging modality is a different risk level than adding data from a different scanner of the same type.", pccp: "UNLIKELY", pccpNote: "Fundamentally changes input type. Likely changes labeling/intended use." },
      { name: "Label corrections / re-annotation", desc: "Correcting erroneous labels in the existing training dataset.", example: "Re-reading and correcting 200 mislabeled pathology slides from quality audit.", misclass: "Sometimes confused with 'label redefinition' (Clinical Output category). Correcting errors in existing labels ≠ changing the definition of what constitutes a positive case. If you're changing the DEFINITION (e.g., stenosis threshold from >50% to >70%), that belongs in Clinical Output, not here.", pccp: "CONDITIONAL", pccpNote: "Define max % labels changed + demonstrate decision boundary stability." },
    ],
    classificationGuidance: "Teams often confuse 'same distribution' with 'new sites' when data comes from the same hospital system but a newly opened facility. Verify: is the site listed in your original clearance documentation?",
    boundaryNote: "If same-distribution data comes from a time period with different disease prevalence, the underlying distribution may have shifted."
  },
  "Model Architecture": {
    types: [
      { name: "Hyperparameter tuning (within predefined bounds)", desc: "Adjusting hyperparameters without changing the model architecture.", example: "Changing learning rate from 0.001 to 0.0005; adjusting dropout from 0.3 to 0.5.", misclass: "Often confused with architecture changes. Hyperparameter tuning within an architecture ≠ changing the architecture itself, even if the parameter change is large. But if the change alters the model's computational graph (e.g., number of layers, attention heads), it's an architecture change.", pccp: "TYPICAL", pccpNote: "Define acceptable parameter ranges + acceptance criteria." },
      { name: "Layer addition / removal", desc: "Adding or removing layers from the existing model architecture.", example: "Adding a dropout layer; removing a pooling layer; adding an attention head.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Requires failure mode analysis comparing old vs new architecture." },
      { name: "Architecture change (same family)", desc: "Changing to a different architecture within the same model family.", example: "Upgrading from ResNet-50 to ResNet-101; BERT-base to BERT-large.", misclass: "The boundary between 'same family' and 'different family' is not always clear. CNN variants (ResNet, DenseNet, EfficientNet) are generally same-family. CNN-to-Transformer (ResNet-to-ViT) is different-family. If in doubt, classify as 'different family' (more conservative).", pccp: "CONDITIONAL", pccpNote: "Robust protocol with parity criteria + failure mode analysis." },
      { name: "Architecture change (new family)", desc: "Switching to a fundamentally different model architecture family.", example: "Switching from CNN (ResNet) to Transformer (ViT); random forest to deep learning.", misclass: "Sometimes underestimated when moving between related families (e.g., CNN to Vision Transformer). Different architecture families have fundamentally different failure modes and interpretability.", pccp: "UNLIKELY", pccpNote: "Fundamentally different risk profile and failure modes. New submission is the expected pathway, though a highly robust PCCP could theoretically cover this if specifically authorized." },
      { name: "Compression / quantization", desc: "Reducing model size through pruning, quantization, or distillation.", example: "Quantizing 32-bit model to 8-bit for edge deployment; knowledge distillation to smaller model.", misclass: "Confused with 'architecture change' when distillation changes the student model architecture. If the compressed model has a different architecture, classify as architecture change instead. This applies when architecture is preserved but model is made smaller/faster.", pccp: "TYPICAL", pccpNote: "Validate performance equivalence post-optimization, especially subgroups." },
    ],
    classificationGuidance: "Hyperparameter tuning 'within bounds' requires bounds to be predefined in an authorized PCCP. If no bounds exist, this is an architecture change requiring a new submission.",
    boundaryNote: "Quantization may change numerical precision enough to shift model outputs on edge cases — validate with your full test suite."
  },
  "Preprocessing & Feature Engineering": {
    types: [
      { name: "New preprocessing step", desc: "Adding a new data preprocessing step not in the original pipeline.", example: "Adding a denoising step before image input; adding text normalization for clinical notes.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Validate model performance maintained with new pipeline." },
      { name: "Normalization change", desc: "Changing how input data is normalized or standardized.", example: "Switching from min-max to z-score normalization; changing image resizing algorithm.", misclass: "Confused with 'SBOM dependency update' (Deployment category) when a framework update changes default normalization behavior. If the preprocessing change is intentional, classify here. If it's an incidental side effect of a dependency update, classify under Deployment.", pccp: "TYPICAL", pccpNote: "Validate output equivalence with different normalization." },
      { name: "Feature addition / removal", desc: "Adding or removing input features from the model.", example: "Adding patient age as a model input; removing a feature found to be a proxy for race.", misclass: "Confused with 'New modality' (Training Data category) when new features require new raw data at inference time. If the feature derives from EXISTING inputs, it belongs here. If it requires NEW inputs at deployment, it belongs under Training Data.", pccp: "CONDITIONAL", pccpNote: "Assess for unintended proxy variables correlated with demographics." },
      { name: "Feature engineering change", desc: "Modifying how existing features are computed or transformed.", example: "Changing from manual to automated feature selection; modifying derived feature calculations.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Document feature rationale. Validate no unintended bias introduction." },
      { name: "Augmentation strategy change", desc: "Changing the data augmentation strategy used during training.", example: "Adding rotation augmentation; changing crop ratios; adding synthetic noise injection.", misclass: "Confused with 'Hyperparameter tuning' (Architecture category) when augmentation parameters (rotation angle, crop size) are adjusted. Augmentation changes affect the effective training distribution; hyperparameter changes affect training dynamics.", pccp: "CONDITIONAL", pccpNote: "Validate no unintended class imbalance or distribution shift." },
    ],
    classificationGuidance: "A 'normalization change' may appear minor but could affect model behavior significantly if the input distribution shifts.",
    boundaryNote: "Feature removal may improve overall metrics but degrade subgroup performance."
  },
  "Clinical Output & Decision Thresholds": {
    types: [
      { name: "Decision threshold adjustment", desc: "Changing the decision threshold for clinical classification.", example: "Moving binary classification threshold from 0.5 to 0.6 to reduce false positives.", misclass: "Often confused with 'Output format change.' Threshold adjustment changes the DECISION the device makes; format change only changes how it looks. Also confused with 'New output class' when splitting a binary output into multiple risk levels — that's a new output type, not a threshold adjustment.", pccp: "CONDITIONAL", pccpNote: "PCCP must define acceptable threshold range + clinical impact bounds." },
      { name: "New output class / label", desc: "Adding a new output category or diagnostic capability.", example: "Adding 'pneumothorax' detection to a device cleared only for 'nodule' detection.", misclass: "This is the second most commonly misclassified change type. Teams classify new output classes as threshold adjustments or UI changes. The test: does the device now diagnose, detect, or classify something it couldn't before? If yes, this almost always constitutes an intended use expansion.", pccp: "UNLIKELY", pccpNote: "Likely constitutes a change to clinical function / intended use. New submission required unless the PCCP specifically authorized additional output classes within defined bounds." },
      { name: "Output format change", desc: "Changing how model output is presented without changing the model.", example: "Changing from numeric probability to color-coded risk categories.", misclass: "Often confused with 'Decision threshold adjustment.' A display change with NO operating point change is fundamentally different from a threshold change. Also confused with 'UI redesign' (Labeling category) — this specifically covers model output display, not broader UI.", pccp: "CONDITIONAL", pccpNote: "Usability assessment confirms no negative clinical interpretation impact." },
      { name: "Confidence score recalibration", desc: "Changing probability calibration method without retraining the model.", example: "Switching from Platt scaling to isotonic regression for probability calibration.", misclass: "Confused with 'Decision threshold adjustment' when recalibration effectively shifts the operating point. Recalibration changes PROBABILITY VALUES; threshold adjustment changes where the DECISION BOUNDARY is placed.", pccp: "TYPICAL", pccpNote: "Validate calibration quality (ECE, reliability diagram) post-change." },
      { name: "Clinical alert threshold change", desc: "Changing thresholds that trigger clinical alerts or notifications.", example: "Lowering the alert threshold for critical findings; adding a new urgency tier.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Assess clinical workflow impact. Alert fatigue is a safety concern." },
    ],
    classificationGuidance: "Adding a new output class almost always constitutes an intended use change — even if the underlying model architecture is unchanged.",
    boundaryNote: "Threshold adjustments affect sensitivity/specificity tradeoffs and may require clinical performance validation."
  },
  "Intended Use / Indications for Use": {
    types: [
      { name: "New clinical indication", desc: "Changing the fundamental intended use or clinical purpose of the device.", example: "Changing from 'screening aid' to 'diagnostic device'; from 'triage' to 'detection'.", misclass: "Rarely misclassified directly, but often the TRUE classification for changes teams have classified under other categories. Any change that expands WHAT the device does should be evaluated here first.", pccp: "NO", pccpNote: "Requires new submission. Per the Marketing Submission Recommendations for a PCCP for AI-Enabled Device Software Functions Guidance (Dec 2024, reissued Aug 2025), PCCPs should generally maintain the device's intended use; fundamental changes to clinical purpose are outside PCCP scope." },
      { name: "Expanded patient population", desc: "Expanding the intended patient population beyond original clearance.", example: "Adding pediatric indication to an adult-cleared device.", misclass: "Often misclassified as 'expanded demographics' under Training Data. Population expansion in intended use ≠ demographic expansion in data. Check your clearance letter.", pccp: "NO", pccpNote: "New clinical evidence typically required. New submission required." },
      { name: "New clinical setting", desc: "Expanding from the cleared clinical setting to new environments.", example: "Expanding from hospital radiology suite to urgent care clinics; from in-clinic to telehealth.", misclass: null, pccp: "NO", pccpNote: "Different settings introduce different user expertise, environmental conditions. New submission likely." },
      { name: "Expanded anatomical region", desc: "Expanding the device to cover new anatomical regions.", example: "Expanding from chest X-ray analysis to abdominal X-ray analysis.", misclass: null, pccp: "NO", pccpNote: "New anatomical region = new clinical capability. New submission required." },
      { name: "Changed severity scope", desc: "Changing the severity range the device is intended to address.", example: "Expanding from detecting moderate-severe disease to also detecting mild cases.", misclass: null, pccp: "NO", pccpNote: "Changes the clinical claims and risk profile. New submission required." },
    ],
    classificationGuidance: null,
    boundaryNote: "Changes in this category generally require a new submission. PCCPs are intended to be focused and bounded within the originally reviewed device scope, and this tool does not treat intended-use changes as routine PCCP implementations. Consult FDA via Q-Submission for intended use-adjacent changes.",
  },
  "Deployment & Infrastructure": {
    types: [
      { name: "Cloud / edge migration", desc: "Moving model between deployment environments.", example: "Migrating from cloud to edge deployment; changing cloud provider (AWS to Azure).", misclass: "Confused with 'SBOM dependency update' when the deployment change requires a different inference framework. If you're changing from TensorFlow Serving to ONNX Runtime as part of deployment, both may apply.", pccp: "TYPICAL", pccpNote: "Validate performance equivalence in new environment. Check latency." },
      { name: "Hardware platform change", desc: "Changing the hardware the model runs on.", example: "Moving from GPU to TPU inference; upgrading GPU generation.", misclass: null, pccp: "TYPICAL", pccpNote: "Validate numerical equivalence on new hardware." },
      { name: "Third-party dependency update", desc: "Changing an external model, API, or service the device depends on.", example: "Cloud AI vendor updates their preprocessing API; third-party NLP service upgrades.", misclass: "Confused with 'Base model swap' (GenAI category) when the third-party model IS the foundation model. Also confused with 'SBOM dependency update' when the update is to an ML framework rather than an external service.", pccp: "CONDITIONAL", pccpNote: "Requires API version locking OR continuous monitoring + re-validation." },
      { name: "API / integration interface change", desc: "Changing how the device integrates with clinical systems.", example: "Adding HL7 FHIR interface; changing DICOM handling; new EHR integration.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Validate data integrity and clinical workflow are maintained." },
      { name: "Scaling / performance optimization", desc: "Optimizing system performance without changing model behavior.", example: "Adding load balancing; optimizing batch inference; caching strategies.", misclass: null, pccp: "TYPICAL", pccpNote: "Verify zero impact on model output. Document performance benchmarks." },
    ],
    classificationGuidance: "A 'third-party dependency update' may appear low-risk but could change model behavior if the dependency affects data processing or inference.",
    boundaryNote: "Cloud migration may introduce latency that affects real-time clinical decision support."
  },
  "Continuous Learning / Periodic Retraining": {
    types: [
      { name: "Periodic retraining (same protocol)", desc: "Periodic retraining on new data with locked architecture per predefined protocol.", example: "Quarterly retraining using accumulated data, same architecture and acceptance criteria.", misclass: "Confused with 'Automated updates' when the retraining is triggered automatically. The distinction: periodic retraining = human initiates each cycle; automated updates = system triggers based on thresholds.", pccp: "CONDITIONAL", pccpNote: "PCCP must specify: trigger, data requirements, training procedure, acceptance criteria, rollback." },
      { name: "Adaptive learning activation", desc: "Enabling automated model updates triggered by data/performance thresholds.", example: "Auto-retraining when AUC drops below 0.90, with auto-rollback if criteria not met.", misclass: "Often confused with 'Periodic retraining.' Automated updates WITH guardrails ≠ fully adaptive online learning WITHOUT bounds. Ensure guardrails are defined.", pccp: "CONDITIONAL", pccpNote: "Strict guardrails required: perf bounds, auto-rollback, human oversight, drift monitoring." },
      { name: "Drift correction update", desc: "Model update specifically to address detected data or concept drift.", example: "Retraining to correct for population shift detected by monitoring system.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Document drift evidence, correction approach, and validation results." },
      { name: "Federated learning round", desc: "Aggregating model updates trained locally across multiple sites.", example: "Federated averaging across 12 hospitals, aggregating weight updates quarterly.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Protocol must define: aggregation algorithm, convergence criteria, site quality, poisoning detection." },
    ],
    classificationGuidance: "Periodic retraining requires a PCCP with predefined retraining protocol, acceptance criteria, and monitoring plan. Without an authorized PCCP, each retraining cycle is assessed as a discrete change.",
    boundaryNote: "Federated learning introduces data heterogeneity that may not be visible in aggregate performance metrics."
  },
  "Labeling & Clinical User Interface": {
    types: [
      { name: "Clinical display change", desc: "Changing how clinical results are displayed to users.", example: "Redesigning results dashboard; changing information hierarchy; modifying color coding.", misclass: "Confused with 'Output format change' (Clinical Output category). The distinction: this covers BROADER UI changes; Output format specifically covers model output display.", pccp: "CONDITIONAL", pccpNote: "Human factors / usability assessment likely required." },
      { name: "User interface redesign", desc: "Significant redesign of the clinical user interface.", example: "Complete workflow redesign; new navigation pattern; tablet-to-desktop migration.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Full usability evaluation in target clinical environment." },
      { name: "Warning / instruction update", desc: "Updating warnings, contraindications, or instructions for use.", example: "Adding clearer IFU; updating contraindication language; IFU translations.", misclass: "If the 'clarification' adds new warnings or changes contraindication language, it may not qualify as clarification-only. New warnings that change clinical behavior should be assessed under risk significance.", pccp: "TYPICAL", pccpNote: "Documentation only if purely clarification. New warnings → assess under risk rules." },
      { name: "Report format change", desc: "Changing the format or structure of clinical reports.", example: "Restructuring radiology report output; changing report sections; adding fields.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Assess whether report structure affects clinical interpretation." },
      { name: "Explainability / transparency change", desc: "Adding, removing, or modifying model interpretability outputs.", example: "Adding Grad-CAM heatmap overlay; changing SHAP explanation methodology; removing confidence intervals.", misclass: "Confused with 'Output format change' when explainability outputs are displayed alongside main predictions. This changes the EXPLANATION mechanism; format change changes the DISPLAY format.", pccp: "CONDITIONAL", pccpNote: "Human factors assessment for clinical interpretation impact. The AI-Enabled Device Software Functions: Lifecycle Management Guidance (Jan 2025 draft — not yet finalized; verify current status at fda.gov) emphasizes clinically relevant explanations." },
    ],
    classificationGuidance: "UI changes that alter how clinical information is presented to clinicians may constitute an intended use change even if the underlying algorithm is unchanged.",
    boundaryNote: "Explainability changes (per the AI-Enabled Device Software Functions: Lifecycle Management Guidance (Jan 2025 draft — not yet finalized; verify current status at fda.gov)) may affect how clinicians interpret and act on AI outputs."
  },
  "Foundation Model / Generative AI": {
    types: [
      { name: "Base / foundation model swap", desc: "Replacing the underlying foundation model with a different model or version.", example: "Upgrading from GPT-4 to GPT-5; switching from LLaMA to Mistral; updating Claude version.", misclass: "Confused with 'Fine-tuning update' when 'upgrading' within the same model family (e.g., GPT-4 to GPT-4 Turbo). Minor version updates within same base may qualify as fine-tuning if base weights haven't fundamentally changed. Major version changes are always a model swap.", pccp: "UNLIKELY", pccpNote: "Fundamentally different base model with unpredictable behavior changes. New submission almost always required. Consult your specific authorized PCCP scope." },
      { name: "Fine-tuning update", desc: "Fine-tuning a foundation model on domain-specific clinical data.", example: "LoRA fine-tuning on 50K radiology reports; RLHF with clinician preferences.", misclass: "Sometimes confused with 'Prompt changes.' Fine-tuning changes MODEL WEIGHTS; prompt engineering only changes the INPUT to a frozen model. Also confused with 'Base model swap' when extensive fine-tuning effectively creates a new model.", pccp: "CONDITIONAL", pccpNote: "Very robust protocol required: hallucination testing, safety regression, red-teaming, clinical accuracy." },
      { name: "Prompt / instruction template change", desc: "Modifying system instructions, few-shot examples, or controlled prompt/configuration elements.", example: "Changing system prompt to include new output formatting rules; adding few-shot examples for new report template.", misclass: "Sometimes confused with 'Fine-tuning.' Prompt changes do NOT change model weights — they are input changes. But they can still significantly alter clinical behavior. Also confused with 'RAG update' when prompt changes include instructions about knowledge retrieval.", pccp: "CONDITIONAL", pccpNote: "PCCP must define acceptable prompt scope, require output validation, include regression testing. Prompts as controlled documents." },
      { name: "RAG knowledge base update", desc: "Updating the retrieval-augmented generation knowledge base or retrieval system.", example: "Adding new clinical guidelines to RAG corpus; updating drug interaction database.", misclass: "Confused with 'Prompt changes' when knowledge is embedded in the prompt via few-shot examples rather than a separate retrieval system. If clinical knowledge is in the prompt, it's a prompt change. If it's in an external knowledge base, it's a RAG update.", pccp: "CONDITIONAL", pccpNote: "Define approved sources, update protocol, content validation by clinical SME." },
      { name: "Guardrail / safety filter modification", desc: "Adding, removing, or modifying safety guardrails or content filters.", example: "Tightening output filter to block off-label recommendations; loosening guardrails for new drug class.", misclass: "Sometimes classified as 'UI change' when guardrails affect output display. If the change controls WHAT the model can say (content filtering), it's a guardrail change. If it only controls HOW output is formatted, it's a UI change.", pccp: "CONDITIONAL", pccpNote: "Adding guardrails = favorable. Removing/loosening = triggers risk assessment. Red-team/adversarial testing is strongly recommended." },
      { name: "Output constraint change", desc: "Modifying constraints on model output format, length, or structure.", example: "Changing from structured JSON output to free-text; adding output length limits.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Validate output quality and clinical interpretation under new constraints." },
      { name: "Adversarial robustness update", desc: "Updating defenses against adversarial inputs or prompt injection.", example: "Adding input sanitization; updating prompt injection detection; hardening against jailbreaks.", misclass: null, pccp: "TYPICAL", pccpNote: "Generally positive change. Validate no impact on legitimate clinical queries." },
      { name: "Embedding model change", desc: "Changing the embedding model used for retrieval or similarity computation.", example: "Switching from text-embedding-ada-002 to text-embedding-3-large.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Validate retrieval quality and relevance maintained with new embeddings." },
    ],
    classificationGuidance: "Prompt changes are often treated as 'configuration,' but for generative AI medical devices, prompts function as part of the device design specification under general design control principles and should be version-controlled. FDA PCCP Final Guidance (Dec 2024, reissued Aug 2025) §VI discusses describing modifications in a PCCP, which logically extends to prompt elements — version control is strongly recommended best practice, not a separately enumerated FDA requirement.",
    boundaryNote: "Foundation model updates from upstream providers may change behavior in ways not captured by standard validation suites."
  },
  "Post-Market Surveillance": {
    types: [
      { name: "Monitoring threshold change", desc: "Modifying the thresholds that trigger monitoring alerts or reviews.", example: "Changing from monthly to weekly performance reviews; raising drift detection threshold.", misclass: "Confused with 'Drift detection recalibration' when threshold changes specifically affect drift detection. This covers OVERALL monitoring methodology; drift detection covers the specific detection algorithm.", pccp: "TYPICAL", pccpNote: "Documentation + QMS update. Ensure no reduction in monitoring capability." },
      { name: "Alert criteria update", desc: "Updating the criteria for post-market alerts and notifications.", example: "Adding new fairness metrics to monitoring dashboard; changing alert severity criteria.", misclass: null, pccp: "TYPICAL", pccpNote: "Documentation + QMS update." },
      { name: "Drift detection recalibration", desc: "Modifying how data drift or performance drift is detected.", example: "Switching from statistical process control to ML-based drift detection; changing response protocol.", misclass: null, pccp: "CONDITIONAL", pccpNote: "Validate detection sensitivity maintained or improved. Weakening detection = risk assessment." },
    ],
    classificationGuidance: null,
    boundaryNote: "Changing monitoring thresholds may mask emerging safety signals."
  },
  "Cybersecurity": {
    types: [
      { name: "Vulnerability patch", desc: "Patching a known security vulnerability.", example: "Patching TLS vulnerability; fixing authentication bypass; addressing CVE.", misclass: "Must have ZERO performance impact on device function to qualify for cybersecurity exemption. FDA requires appropriate analysis/verification/validation demonstrating the change is solely to strengthen cybersecurity with no other impact. Internal heuristic: bitwise output comparison is a defensible but more-stringent-than-required verification approach.", pccp: "EXEMPT", pccpNote: "Cybersecurity Exemption. Documentation only if zero performance impact verified." },
      { name: "Encryption update", desc: "Upgrading encryption protocols or algorithms.", example: "Upgrading from TLS 1.2 to TLS 1.3; changing encryption algorithm.", misclass: null, pccp: "EXEMPT", pccpNote: "Cybersecurity Exemption if zero performance impact." },
      { name: "Authentication / access control change", desc: "Modifying user authentication or access control mechanisms.", example: "Adding MFA; updating role-based access; changing session management.", misclass: null, pccp: "EXEMPT", pccpNote: "Cybersecurity Exemption if zero performance impact." },
      { name: "SBOM dependency update", desc: "Updating software dependencies for security purposes.", example: "Updating NumPy for security patch; upgrading ONNX runtime for vulnerability fix.", misclass: "If the SBOM update changes any ML framework dependency (PyTorch, TensorFlow, ONNX), floating-point behavior may change. This exits the cybersecurity exemption — classify under Preprocessing instead if inference behavior changes.", pccp: "EXEMPT", pccpNote: "Cybersecurity Exemption ONLY if zero inference impact. Framework updates may change floating-point behavior." },
      { name: "Penetration test remediation", desc: "Implementing fixes identified during penetration testing.", example: "Fixing API vulnerabilities; hardening input validation; closing network exposure.", misclass: null, pccp: "EXEMPT", pccpNote: "Cybersecurity Exemption if zero performance impact." },
    ],
    classificationGuidance: "Pure cybersecurity patches with zero functional impact can qualify for the Cybersecurity Exemption. However, if the patch changes any data processing, model inference, or clinical output pathway, it does not qualify.",
    boundaryNote: "SBOM dependency updates may transitively affect ML libraries (e.g., NumPy, TensorFlow version changes)."
  },
};
